package com.helper.pojo;

import javax.persistence.*;

@Table(name="student")
public class Student {
    @Id
    @Column(name = "s_id")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private String sId;

    @Column(name = "s_password")
    private String sPassword;

    @Column(name = "s_name")
    private String sName;

    @Column(name = "c_id")
    private String cId;


    public String getcId() {
        return cId;
    }

    public void setcId(String cId) {
        this.cId = cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.s_id
     *
     * @return the value of student.s_id
     *
     * @mbg.generated Mon Sep 10 16:38:14 CST 2018
     */
    public String getsId() {
        return sId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.s_id
     *
     * @param sId the value for student.s_id
     *
     * @mbg.generated Mon Sep 10 16:38:14 CST 2018
     */
    public void setsId(String sId) {
        this.sId = sId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.s_password
     *
     * @return the value of student.s_password
     *
     * @mbg.generated Mon Sep 10 16:38:14 CST 2018
     */
    public String getsPassword() {
        return sPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.s_password
     *
     * @param sPassword the value for student.s_password
     *
     * @mbg.generated Mon Sep 10 16:38:14 CST 2018
     */
    public void setsPassword(String sPassword) {
        this.sPassword = sPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.s_name
     *
     * @return the value of student.s_name
     *
     * @mbg.generated Mon Sep 10 16:38:14 CST 2018
     */
    public String getsName() {
        return sName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.s_name
     *
     * @param sName the value for student.s_name
     *
     * @mbg.generated Mon Sep 10 16:38:14 CST 2018
     */
    public void setsName(String sName) {
        this.sName = sName;
    }
}