package com.helper.pojo;

import org.springframework.stereotype.Component;

import javax.persistence.*;

@Table(name = "teacher")
public class Teacher {
    @Id
    @Column(name = "t_id")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private String tId;

    @Column(name = "t_password")
    private String tPassword;

    @Column(name = "t_name")
    private String tName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.t_id
     *
     * @return the value of teacher.t_id
     *
     * @mbg.generated Mon Sep 10 16:38:14 CST 2018
     */
    public String gettId() {
        return tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.t_id
     *
     * @param tId the value for teacher.t_id
     *
     * @mbg.generated Mon Sep 10 16:38:14 CST 2018
     */
    public void settId(String tId) {
        this.tId = tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.t_password
     *
     * @return the value of teacher.t_password
     *
     * @mbg.generated Mon Sep 10 16:38:14 CST 2018
     */
    public String gettPassword() {
        return tPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.t_password
     *
     * @param tPassword the value for teacher.t_password
     *
     * @mbg.generated Mon Sep 10 16:38:14 CST 2018
     */
    public void settPassword(String tPassword) {
        this.tPassword = tPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.t_name
     *
     * @return the value of teacher.t_name
     *
     * @mbg.generated Mon Sep 10 16:38:14 CST 2018
     */
    public String gettName() {
        return tName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.t_name
     *
     * @param tName the value for teacher.t_name
     *
     * @mbg.generated Mon Sep 10 16:38:14 CST 2018
     */
    public void settName(String tName) {
        this.tName = tName;
    }
}